webdriver {
  driver = chrome
  autodownload = true
}

headless.mode = false

serenity {
  browser.width = 1920
  browser.height = 1080
  take.screenshots = AFTER_EACH_STEP
}

environments {
  default {
    webdriver.base.url = "http://opencart.abstracta.us"
  }
}
